// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANITmqBTsttfzr5bGJQdbt--VH_Q5kgEc',
    appId: '1:813524140851:web:276a54fd412cde375fb446',
    messagingSenderId: '813524140851',
    projectId: 'noteapp-ba373',
    authDomain: 'noteapp-ba373.firebaseapp.com',
    storageBucket: 'noteapp-ba373.firebasestorage.app',
    measurementId: 'G-PKM42M2471',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1_jBVwNuNAkxPmoHXL82TaDWlfrPRpCA',
    appId: '1:813524140851:android:3a23f1a1c39b53ca5fb446',
    messagingSenderId: '813524140851',
    projectId: 'noteapp-ba373',
    storageBucket: 'noteapp-ba373.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnFeIINnlF3uTjhrgoi9kbpO3EDRzR6sE',
    appId: '1:813524140851:ios:c0179ad66f72bd755fb446',
    messagingSenderId: '813524140851',
    projectId: 'noteapp-ba373',
    storageBucket: 'noteapp-ba373.firebasestorage.app',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnFeIINnlF3uTjhrgoi9kbpO3EDRzR6sE',
    appId: '1:813524140851:ios:c0179ad66f72bd755fb446',
    messagingSenderId: '813524140851',
    projectId: 'noteapp-ba373',
    storageBucket: 'noteapp-ba373.firebasestorage.app',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANITmqBTsttfzr5bGJQdbt--VH_Q5kgEc',
    appId: '1:813524140851:web:7408956352dbda135fb446',
    messagingSenderId: '813524140851',
    projectId: 'noteapp-ba373',
    authDomain: 'noteapp-ba373.firebaseapp.com',
    storageBucket: 'noteapp-ba373.firebasestorage.app',
    measurementId: 'G-NFMB3Z8BPD',
  );
}
